/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionLinkTokenRouteImport } from './routes/session/$linkToken'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedHelloWorldGameRouteImport } from './routes/_authenticated/hello-world-game'
import { Route as AuthenticatedStudentDashboardIndexRouteImport } from './routes/_authenticated/student-dashboard/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedCaseloadIndexRouteImport } from './routes/_authenticated/caseload/index'
import { Route as AuthTeacherSignupRouteImport } from './routes/auth/teacher/signup'
import { Route as AuthTeacherLoginRouteImport } from './routes/auth/teacher/login'
import { Route as AuthStudentSignupRouteImport } from './routes/auth/student/signup'
import { Route as AuthStudentLoginRouteImport } from './routes/auth/student/login'
import { Route as AuthenticatedSessionSessionIdRouteImport } from './routes/_authenticated/session/$sessionId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLinkTokenRoute = SessionLinkTokenRouteImport.update({
  id: '/session/$linkToken',
  path: '/session/$linkToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelloWorldGameRoute =
  AuthenticatedHelloWorldGameRouteImport.update({
    id: '/hello-world-game',
    path: '/hello-world-game',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentDashboardIndexRoute =
  AuthenticatedStudentDashboardIndexRouteImport.update({
    id: '/student-dashboard/',
    path: '/student-dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaseloadIndexRoute =
  AuthenticatedCaseloadIndexRouteImport.update({
    id: '/caseload/',
    path: '/caseload/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthTeacherSignupRoute = AuthTeacherSignupRouteImport.update({
  id: '/auth/teacher/signup',
  path: '/auth/teacher/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeacherLoginRoute = AuthTeacherLoginRouteImport.update({
  id: '/auth/teacher/login',
  path: '/auth/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentSignupRoute = AuthStudentSignupRouteImport.update({
  id: '/auth/student/signup',
  path: '/auth/student/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentLoginRoute = AuthStudentLoginRouteImport.update({
  id: '/auth/student/login',
  path: '/auth/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionSessionIdRoute =
  AuthenticatedSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello-world-game': typeof AuthenticatedHelloWorldGameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/session/$linkToken': typeof SessionLinkTokenRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/auth/student/login': typeof AuthStudentLoginRoute
  '/auth/student/signup': typeof AuthStudentSignupRoute
  '/auth/teacher/login': typeof AuthTeacherLoginRoute
  '/auth/teacher/signup': typeof AuthTeacherSignupRoute
  '/caseload': typeof AuthenticatedCaseloadIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello-world-game': typeof AuthenticatedHelloWorldGameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/session/$linkToken': typeof SessionLinkTokenRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/auth/student/login': typeof AuthStudentLoginRoute
  '/auth/student/signup': typeof AuthStudentSignupRoute
  '/auth/teacher/login': typeof AuthTeacherLoginRoute
  '/auth/teacher/signup': typeof AuthTeacherSignupRoute
  '/caseload': typeof AuthenticatedCaseloadIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/hello-world-game': typeof AuthenticatedHelloWorldGameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/session/$linkToken': typeof SessionLinkTokenRoute
  '/_authenticated/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/auth/student/login': typeof AuthStudentLoginRoute
  '/auth/student/signup': typeof AuthStudentSignupRoute
  '/auth/teacher/login': typeof AuthTeacherLoginRoute
  '/auth/teacher/signup': typeof AuthTeacherSignupRoute
  '/_authenticated/caseload/': typeof AuthenticatedCaseloadIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/student-dashboard/': typeof AuthenticatedStudentDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hello-world-game'
    | '/auth/login'
    | '/auth/signup'
    | '/session/$linkToken'
    | '/session/$sessionId'
    | '/auth/student/login'
    | '/auth/student/signup'
    | '/auth/teacher/login'
    | '/auth/teacher/signup'
    | '/caseload'
    | '/onboarding'
    | '/student-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hello-world-game'
    | '/auth/login'
    | '/auth/signup'
    | '/session/$linkToken'
    | '/session/$sessionId'
    | '/auth/student/login'
    | '/auth/student/signup'
    | '/auth/teacher/login'
    | '/auth/teacher/signup'
    | '/caseload'
    | '/onboarding'
    | '/student-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/hello-world-game'
    | '/auth/login'
    | '/auth/signup'
    | '/session/$linkToken'
    | '/_authenticated/session/$sessionId'
    | '/auth/student/login'
    | '/auth/student/signup'
    | '/auth/teacher/login'
    | '/auth/teacher/signup'
    | '/_authenticated/caseload/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/student-dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SessionLinkTokenRoute: typeof SessionLinkTokenRoute
  AuthStudentLoginRoute: typeof AuthStudentLoginRoute
  AuthStudentSignupRoute: typeof AuthStudentSignupRoute
  AuthTeacherLoginRoute: typeof AuthTeacherLoginRoute
  AuthTeacherSignupRoute: typeof AuthTeacherSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$linkToken': {
      id: '/session/$linkToken'
      path: '/session/$linkToken'
      fullPath: '/session/$linkToken'
      preLoaderRoute: typeof SessionLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hello-world-game': {
      id: '/_authenticated/hello-world-game'
      path: '/hello-world-game'
      fullPath: '/hello-world-game'
      preLoaderRoute: typeof AuthenticatedHelloWorldGameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-dashboard/': {
      id: '/_authenticated/student-dashboard/'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caseload/': {
      id: '/_authenticated/caseload/'
      path: '/caseload'
      fullPath: '/caseload'
      preLoaderRoute: typeof AuthenticatedCaseloadIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/teacher/signup': {
      id: '/auth/teacher/signup'
      path: '/auth/teacher/signup'
      fullPath: '/auth/teacher/signup'
      preLoaderRoute: typeof AuthTeacherSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/teacher/login': {
      id: '/auth/teacher/login'
      path: '/auth/teacher/login'
      fullPath: '/auth/teacher/login'
      preLoaderRoute: typeof AuthTeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student/signup': {
      id: '/auth/student/signup'
      path: '/auth/student/signup'
      fullPath: '/auth/student/signup'
      preLoaderRoute: typeof AuthStudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student/login': {
      id: '/auth/student/login'
      path: '/auth/student/login'
      fullPath: '/auth/student/login'
      preLoaderRoute: typeof AuthStudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/session/$sessionId': {
      id: '/_authenticated/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHelloWorldGameRoute: typeof AuthenticatedHelloWorldGameRoute
  AuthenticatedSessionSessionIdRoute: typeof AuthenticatedSessionSessionIdRoute
  AuthenticatedCaseloadIndexRoute: typeof AuthenticatedCaseloadIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedStudentDashboardIndexRoute: typeof AuthenticatedStudentDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHelloWorldGameRoute: AuthenticatedHelloWorldGameRoute,
  AuthenticatedSessionSessionIdRoute: AuthenticatedSessionSessionIdRoute,
  AuthenticatedCaseloadIndexRoute: AuthenticatedCaseloadIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedStudentDashboardIndexRoute:
    AuthenticatedStudentDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  SessionLinkTokenRoute: SessionLinkTokenRoute,
  AuthStudentLoginRoute: AuthStudentLoginRoute,
  AuthStudentSignupRoute: AuthStudentSignupRoute,
  AuthTeacherLoginRoute: AuthTeacherLoginRoute,
  AuthTeacherSignupRoute: AuthTeacherSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
